// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:16f02e7e-c1d4-4896-ac98-9e5bbd36a9a7',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'animalapp-hosting-mobilehub-1402109028',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3b3la1qxnx8xl.cloudfront.net',
    'aws_mobile_analytics_app_id': '390254d92a96479aa48453b7629343ca',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '71a2d523-58ce-4a3c-ab0d-37ffc169c695',
    'aws_project_name': 'AnimalApp-2018-07-22-15-46-56',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'animalapp-mobilehub-1402109028',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_Gs80vf2se',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '1nhh6p1qv2bfhmvgkcid21mc',
}

export default awsmobile;
